// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title    string  `json:"title"`
	Content  *string `json:"content,omitempty"`
	AuthorID string  `json:"authorId"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Post struct {
	ID      string  `json:"id"`
	Title   string  `json:"title"`
	Content *string `json:"content,omitempty"`
	Author  *User   `json:"author"`
}

type Query struct {
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Posts []*Post `json:"posts"`
}
